# Generated by Django 6.0.5 on 2026-05-23 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_days', models.IntegerField(default=0)),
                ('working_days', models.IntegerField(default=0)),
                ('present_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('lop_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('ot_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('basic', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('da', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('special_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transport', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medical', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ot_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pf_employee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('esi_employee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tds', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lop_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payslip_url', models.URLField(blank=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bonus', 'Bonus'), ('reimbursement', 'Reimbursement'), ('deduction', 'Deduction'), ('arrear', 'Arrear')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments_added', to=settings.AUTH_USER_MODEL)),
                ('payroll_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='payroll.payrollentry')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processed', 'Processed'), ('approved', 'Approved'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payroll_runs', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='payroll_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='payroll.payrollrun'),
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('ctc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('basic', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('da', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('special_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transport', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medical', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pf_employee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('esi_employee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pf_employer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('esi_employer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_structures', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='salary_structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.salarystructure'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollentry',
            unique_together={('payroll_run', 'employee')},
        ),
    ]
