# Generated by Django 6.0.5 on 2026-05-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarystructure',
            name='basic',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='da',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='esi_employee',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='esi_employer',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='hra',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='pf_employee',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='pf_employer',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='special_allowance',
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='basic_percent',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=5),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='da_percent',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='esi_percent',
            field=models.DecimalField(decimal_places=2, default=0.75, max_digits=5),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='hra_percent',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='pf_percent',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=5),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='medical',
            field=models.DecimalField(decimal_places=2, default=1250, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='pt',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='transport',
            field=models.DecimalField(decimal_places=2, default=1600, max_digits=10),
        ),
    ]
