# Generated by Django 6.0.5 on 2026-05-28 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_remove_salarystructure_basic_and_more'),
        ('payroll', '0007_add_holiday_fields'),
    ]

    operations = [
    ]
