# Generated by Django 6.0.5 on 2026-05-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_merge_20260528_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollentry',
            name='comp_off_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='extra_work_dates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='extra_work_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='extra_work_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
