# Generated by Django 6.0.5 on 2026-05-23 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('module', models.CharField(choices=[('employees', 'Employees'), ('departments', 'Departments'), ('attendance', 'Attendance'), ('leave', 'Leave'), ('payroll', 'Payroll'), ('reports', 'Reports'), ('users', 'Users'), ('settings', 'Settings')], max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['module', 'code'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superadmin', 'SuperAdmin'), ('admin', 'Admin'), ('manager', 'Manager'), ('hr', 'HR'), ('employee', 'Employee')], max_length=20)),
                ('is_granted', models.BooleanField(default=False)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='utils.permission')),
            ],
            options={
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
