# Generated by Django 6.0.5 on 2026-05-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_userpermissionoverride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('employees', 'Employees'), ('departments', 'Departments'), ('attendance', 'Attendance'), ('leave', 'Leave'), ('payroll', 'Payroll'), ('reports', 'Reports'), ('users', 'Users'), ('settings', 'Settings'), ('notifications', 'Notifications')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userpermissionoverride',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
