# Generated by Django 6.0.5 on 2026-06-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_alter_permission_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('employees', 'Employees'), ('departments', 'Departments'), ('attendance', 'Attendance'), ('leave', 'Leave'), ('payroll', 'Payroll'), ('reports', 'Reports'), ('users', 'Users'), ('settings', 'Settings'), ('notifications', 'Notifications'), ('support_tickets', 'Support Tickets')], max_length=50),
        ),
    ]
