# Generated by Django 6.0.5 on 2026-06-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_alter_rolepermission_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('employees', 'Employees'), ('departments', 'Departments'), ('attendance', 'Attendance'), ('leave', 'Leave'), ('payroll', 'Payroll'), ('reports', 'Reports'), ('users', 'Users'), ('settings', 'Settings'), ('notifications', 'Notifications'), ('support_tickets', 'Support Tickets'), ('affiliate', 'Affiliate'), ('leads', 'Leads'), ('tasks', 'Tasks'), ('revenue', 'Revenue')], max_length=50),
        ),
    ]
