# Generated by Django 6.0.5 on 2026-05-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customrole_user_custom_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrole',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
