# Generated by Django 6.0.5 on 2026-06-02 07:37

from django.db import migrations, models


def seed_default_tenant(apps, schema_editor):
    Tenant = apps.get_model('accounts', 'Tenant')
    Tenant.objects.get_or_create(
        code='default',
        defaults={'name': 'Default Tenant', 'is_active': True},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_tenant_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customrole',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=64),
        ),
        migrations.RunPython(seed_default_tenant, migrations.RunPython.noop),
    ]
