# Generated by Django 6.0.5 on 2026-06-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_leadoption_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Interested', 'Interested'), ('Follow-Up Pending', 'Follow-Up Pending'), ('Admission Confirmed', 'Admission Confirmed'), ('Rejected', 'Rejected')], default='New', max_length=50),
        ),
    ]
