# Generated by Django 6.0.5 on 2026-05-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_office_location_and_location_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('late', 'Late'), ('holiday', 'Holiday'), ('weekend', 'Weekend'), ('leave', 'On Leave'), ('pending', 'Pending Correction')], default='absent', max_length=20),
        ),
    ]
