# Generated by Django 6.0.5 on 2026-06-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendancerecord_shift_type_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=64),
        ),
        migrations.AddField(
            model_name='attendanceregularization',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=64),
        ),
        migrations.AddField(
            model_name='holiday',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=64),
        ),
        migrations.AddField(
            model_name='officelocation',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=64),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('tenant_id', 'date')},
        ),
    ]
