# Generated by Django 6.0.5 on 2026-05-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='value_type',
            field=models.CharField(choices=[('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean (true/false)'), ('string', 'Text'), ('json', 'JSON'), ('time', 'Time (HH:MM)')], default='string', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('leave_applied', 'Leave Applied'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('leave_cancelled', 'Leave Cancelled'), ('attendance_absent', 'Attendance Absent'), ('regularization', 'Regularization Request'), ('payroll_processed', 'Payroll Processed'), ('leave_balance_low', 'Leave Balance Low'), ('new_account', 'New Account Created'), ('general', 'General'), ('policy_updated', 'Policy Updated')], default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='category',
            field=models.CharField(choices=[('attendance', 'Attendance'), ('leave', 'Leave'), ('payroll', 'Payroll'), ('general', 'General'), ('policy', 'Policies')], default='general', max_length=30),
        ),
    ]
