# Generated by Django 6.0.5 on 2026-06-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_remove_notification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=64),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='systemsetting',
            unique_together={('tenant_id', 'key')},
        ),
    ]
