ALL_PERMISSIONS = [
    ('view_users', 'View all users', 'users'),
    ('create_user', 'Create user', 'users'),
    ('edit_user', 'Edit user', 'users'),
    ('create_employee', 'Create employee', 'employees'),
    ('edit_employee', 'Edit employee', 'employees'),
    ('delete_employee', 'Deactivate employee', 'employees'),
    ('view_employees', 'View employees list', 'employees'),
    ('manage_permissions', 'Manage role permissions', 'settings'),
    ('view_departments', 'View departments', 'departments'),
    ('create_department', 'Create department', 'departments'),
    ('edit_department', 'Edit department', 'departments'),
    ('delete_department', 'Delete department', 'departments'),
    ('view_attendance', 'View own attendance', 'attendance'),
    ('view_team_attendance', 'View team attendance', 'attendance'),
    ('approve_regularize', 'Approve regularization', 'attendance'),
    ('manage_settings', 'Manage system settings', 'settings'),
    ('view_leave', 'View own leave', 'leave'),
    ('apply_leave', 'Apply for leave', 'leave'),
    ('cancel_leave', 'Cancel leave request', 'leave'),
    ('view_all_leave', 'View all leave requests', 'leave'),
    ('approve_leave', 'Approve/reject leave', 'leave'),
    ('configure_leave', 'Configure leave types', 'leave'),
    ('view_salary', 'View salary structures', 'payroll'),
    ('configure_salary', 'Create and edit salary', 'payroll'),
    ('view_payroll', 'View payroll runs', 'payroll'),
    ('process_payroll', 'Create and process payroll', 'payroll'),
    ('approve_payroll', 'Approve and lock payroll', 'payroll'),
    ('view_payslip', 'View own payslip', 'payroll'),
    ('view_reports', 'View reports', 'reports'),
    ('self_reports', 'View own reports', 'reports'),
    ('export_reports', 'Export reports', 'reports'),
    ('raise_support_ticket', 'Raise support ticket', 'support_tickets'),
    ('view_support_tickets', 'Track own support tickets', 'support_tickets'),
    ('manage_support_tickets', 'Resolve all support tickets', 'support_tickets'),
    ('manage_support_ticket_types', 'Manage ticket issue types', 'support_tickets'),
    ('view_affiliate', 'View affiliate dashboard', 'affiliate'),
    ('manage_affiliate', 'Manage affiliate workflow', 'affiliate'),
    ('view_leads', 'View leads', 'leads'),
    ('create_lead', 'Create leads', 'leads'),
    ('edit_lead', 'Edit leads', 'leads'),
    ('delete_lead', 'Delete leads', 'leads'),
    ('assign_lead', 'Assign leads to counselors', 'leads'),
    ('view_followups', 'View lead follow ups', 'leads'),
    ('create_followup', 'Create lead follow ups', 'leads'),
    ('manage_lead_forms', 'Manage lead intake forms', 'leads'),
    ('view_lead_analytics', 'View lead analytics', 'leads'),
    ('view_tasks', 'View own tasks', 'tasks'),
    ('view_team_tasks', 'View team tasks', 'tasks'),
    ('create_task', 'Create tasks', 'tasks'),
    ('edit_task', 'Edit tasks', 'tasks'),
    ('delete_task', 'Delete tasks', 'tasks'),
    ('assign_task', 'Assign tasks to employees', 'tasks'),
    ('view_revenue', 'View revenue dashboard', 'revenue'),
    ('manage_revenue', 'Manage revenue records', 'revenue'),
]

ALL_CODES = [code for code, _, _ in ALL_PERMISSIONS]

ROLE_DEFAULTS = {
    'superadmin': ALL_CODES,
    'admin': ALL_CODES,
    'manager': [
        'view_employees', 'view_departments',
        'view_attendance', 'view_team_attendance', 'approve_regularize',
        'view_leave', 'apply_leave', 'cancel_leave',
        'view_all_leave', 'approve_leave',
        'view_payslip', 'view_reports',
        'raise_support_ticket', 'view_support_tickets',
        'view_affiliate', 'view_leads', 'create_lead', 'edit_lead',
        'view_followups', 'create_followup',
        'view_lead_analytics', 'view_tasks', 'view_team_tasks',
        'create_task', 'edit_task', 'assign_task', 'view_revenue',
    ],
    'hr': [
        'view_employees', 'create_employee', 'edit_employee',
        'view_departments', 'create_department', 'edit_department',
        'view_attendance', 'view_team_attendance', 'approve_regularize',
        'manage_settings',
        'view_leave', 'apply_leave', 'cancel_leave',
        'view_all_leave', 'approve_leave', 'configure_leave',
        'view_salary', 'view_payroll', 'view_payslip',
        'view_reports', 'export_reports',
        'raise_support_ticket', 'view_support_tickets',
        'manage_support_tickets', 'manage_support_ticket_types',
        'view_affiliate', 'manage_affiliate',
        'view_leads', 'create_lead', 'edit_lead', 'delete_lead',
        'assign_lead', 'view_followups', 'create_followup',
        'manage_lead_forms', 'view_lead_analytics',
        'view_tasks', 'view_team_tasks', 'create_task', 'edit_task',
        'delete_task', 'assign_task',
        'view_revenue', 'manage_revenue',
    ],
    'counselor': [
        'view_attendance',
        'view_leave', 'apply_leave', 'cancel_leave',
        'view_payslip',
        'raise_support_ticket', 'view_support_tickets',
        'view_leads', 'create_lead', 'edit_lead',
        'view_followups', 'create_followup',
        'view_tasks',
    ],
    'employee': [
        'view_attendance',
        'view_leave', 'apply_leave', 'cancel_leave',
        'view_payslip',
        'raise_support_ticket', 'view_support_tickets',
        'view_tasks', 'view_leads', 'create_followup', 'view_followups',
    ],
}
