# Generated by Django 6.0.5 on 2026-06-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeeprofile_work_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=64),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=64),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='emp_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('tenant_id', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='employeeprofile',
            unique_together={('tenant_id', 'emp_code')},
        ),
    ]
