# Generated by Django 6.0.5 on 2026-06-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=64),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=64),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=64),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='leavetype',
            unique_together={('tenant_id', 'code'), ('tenant_id', 'name')},
        ),
    ]
